os:
  - 'linux'
dist: trusty
language: node_js
node_js:
  - '14.16.0'
cache:
  directories:
    - ./node_modules

before_install:
  - npm install -g npm@6.14.11

install:
  - npm install

script:
  - npm run build
  - npm run test
